version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 25
    assignees:
      - mprins
    labels:
      - "build infrastructure"
      - "dependencies"
    ignore:
      - dependency-name: org.apache.tomcat:tomcat-dbcp
        versions:
          - ">= 10.a"
      - dependency-name: com.microsoft.sqlserver:mssql-jdbc
        versions:
          - "12.3.x"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monday"
      day: saturday
      timezone: Europe/Amsterdam
    labels:
      - "build infrastructure"
    assignees:
      - mprins
