tag-template: "jdbc-util-$NEXT_MINOR_VERSION"
name-template: v$NEXT_MINOR_VERSION 🎁

version-template: "$MAJOR.$MINOR"

template: |
  ## What’s Changed

  $CHANGES

categories:
  - title: 🚨 Removed
    when:
      label: removed
  - title: ⚠️ Deprecated
    when:
      label: deprecated
  - title: 🚀 New features and improvements
    when:
      labels:
        - enhancement
        - feature
  - title: 🐛 Bug Fixes
    when:
      labels:
        - bug
        - fix
        - bugfix
        - regression
        - security
  - title: 📖 Documentation updates
    when:
      label: documentation
  - title: 🔨 Dependency updates
    when:
      label: dependencies
  - title: 🚦 Tests and Infrastructure
    when:
      labels:
        - tests
        - 'build infrastructure'

replacers:
  - search: '/CVE-(\d{4})-(\d+)/g'
    replace: 'https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-$1-$2'
