language: java
dist: bionic

env:
  global:
    - MVN_VERSION="3.6.2"
    - PROFILE="postgresql"

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10-postgis-2.5

services:
  - postgresql

jdk:
#  - openjdk8
  - openjdk11

matrix:
  fast_finish: true
  include:
    - name: "SQL Server 2017"
      dist: xenial
      group: edge
      jdk: openjdk8
      sudo: required
      env:
        - PROFILE="mssql"
    - name: "HSQLDB"
      jdk: openjdk11
      sudo: required
      env:
        - PROFILE="hsqldb"
    - name: "OpenJDK8"
      dist: xenial
      jdk: openjdk8
      sudo: required
      env:
        - PROFILE="postgresql"

# before_cache:

cache:
  directories:
    - $HOME/.m2
    - $HOME/downloads

before_install:
  # installeer een up-2-date Maven versie
  - wget --directory-prefix=$HOME/downloads/ --no-clobber https://www-eu.apache.org/dist/maven/maven-3/$MVN_VERSION/binaries/apache-maven-$MVN_VERSION-bin.zip
  - unzip -qq $HOME/downloads/apache-maven-$MVN_VERSION-bin.zip
  - export M2_HOME=$PWD/apache-maven-$MVN_VERSION
  - export PATH=$M2_HOME/bin:$PATH
  - mvn -v --global-toolchains .travis/toolchains.xml
  - export PAGER=cat
  # hack voor travis xenial images, zie: https://github.com/travis-ci/travis-ci/issues/10290
  #                                 openjdk8 installatie mislukt
  - if [ "$PROFILE" == "mssql" ]; then
      sudo service postgresql stop;
      sh ".travis/install-mssql.sh";
      PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/lib\/jvm\/openjdk11\/bin//');
      JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64;
    elif [ "$PROFILE" == "hsqldb" ]; then
      sudo service postgresql stop;
    else
      sh ".travis/install-pgsql.sh";
    fi

install:
  # install all dependencies + artifacts and create any DB scripts without any testing
  - mvn install -Dmaven.test.skip=true --global-toolchains .travis/toolchains.xml -B -V -e -fae -q -P$PROFILE

before_script:
  - if [ "$PROFILE" == "mssql" ]; then
      sh ".travis/setup-mssql.sh";
    elif [ "$PROFILE" == "hsqldb" ]; then
      sh ".travis/setup-hsqldb.sh";
    else
      sh ".travis/setup-pgsql.sh";
    fi

script:
  # run unit tests 
  - mvn -e test -B --global-toolchains .travis/toolchains.xml -P$PROFILE
  # run integratie tests
  - mvn -e verify -B --global-toolchains .travis/toolchains.xml -P$PROFILE -T1 -Dtest.onlyITs=true
  # test of de javadoc en test-javadoc compliant is met java-8 strict checks
  # altijd doen anders loop je daar met maken van een release tegenaan
  - if [ "$TRAVIS_JDK_VERSION" == openjdk11 ]; then
      mvn javadoc:javadoc --global-toolchains .travis/toolchains.xml;
      mvn javadoc:test-javadoc --global-toolchains .travis/toolchains.xml;
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
