version: "{build}-{branch}"
clone_folder: c:\projects\jdbc-util
clone_depth: 5
skip_tags: true
image: Visual Studio 2022

init:
  - git config --global core.autocrlf input
  - git config --global core.safecrlf true
  - cmd: net start %SQL%
  - choco install codecov

environment:
  JAVA_HOME: C:\Program Files\Java\jdk11
  matrix:
    - SQL: MSSQL$SQL2019
      INSTANCENAME: SQL2019
    - SQL: MSSQL$SQL2017
      INSTANCENAME: SQL2017

matrix:
  fast_finish: false

install:
  - cmd: echo %PATH%
  - cmd: java -version
  - cd C:\projects\jdbc-util
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-http-proxy.ps1'))
  - ps: .\.appveyor\set-maven-proxy.ps1
  # initial build, no testing
  # the `-Dhttps.protocols=TLSv1.1,TLSv1.2` option is to work around https://bugs.openjdk.java.net/browse/JDK-8213202 (needed for java 11.0.2 which has bugs with TLS 1.3)
  - mvn install -Dhttps.protocols=TLSv1.1,TLSv1.2 -Dmaven.test.skip=true -B -V -e -fae -q -Pmssql

build: off

before_test:
# services worden na install gestart en we hebben gegenereerde sql nodig
  - cmd: echo "aanmaken en opzetten STAGING DB"
  - sqlcmd -S (local)\%INSTANCENAME% -U sa -P Password12! -Q "CREATE DATABASE staging" -d "master"
  - dir -w .appveyor\
  - sqlcmd -S (local)\%INSTANCENAME% -U sa -P Password12! -d "staging" -i .\.build\ci\mssql-create-schema.sql
#
  - cmd: echo "computer name:" %COMPUTERNAME%
  - cmd: echo "instance name:" %INSTANCENAME%
  - ps: .\.appveyor\setting-tcp-ip-ports.ps1


test_script:
  # unit tests
  - mvn -Dhttps.protocols=TLSv1.1,TLSv1.2 -e test -B -Pmssql
  # integratie tests
  - mvn -Dhttps.protocols=TLSv1.1,TLSv1.2 -e verify -B -Pmssql -T1 -Dtest.onlyITs=true
  - codecov -v -f target/site/jacoco-it/jacoco.xml target/site/jacoco/jacoco.xml

cache:
  - C:\Users\appveyor\.m2\repository -> pom.xml
