codecov:
  token: c23e7269-c995-47b1-b1a8-9f6be5f70b0d
  bot: 'codecov-io'
  strict_yaml_branch: 'master'
  branch: 'master'
  require_ci_to_pass: true
  notify:
    after_n_builds: 5
    wait_for_ci: true

coverage:
  precision: 0
  round: 'up'
  range: "70...100"
  status:
    changes: false
    patch:
      default:
        target: auto
        threshold: 1%
    project:
      default:
        target: auto
        threshold: 1%

# https://docs.codecov.com/docs/github-checks
github_checks:
  annotations: true

# https://docs.codecov.com/docs/pull-request-comments
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
  after_n_builds: 5