ALTER SESSION SET "_ORACLE_SCRIPT"=true;

-- USER SQL
CREATE USER "JDBCUTIL" IDENTIFIED BY "jdbcutil"  DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "JDBCUTIL" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO "JDBCUTIL" ;
GRANT "RESOURCE" TO "JDBCUTIL" ;
ALTER USER "JDBCUTIL" DEFAULT ROLE "CONNECT","RESOURCE";

GRANT CREATE VIEW TO "JDBCUTIL" ;
GRANT CREATE SYNONYM TO "JDBCUTIL" ;