name: 'Cleanup and Maintainance'

on:
  workflow_dispatch:
  schedule:
    - cron: "19 23 * * 1"

jobs:
  stale:
    runs-on: ubuntu-latest
    name: 'Close Stale PRs'
    permissions:
      pull-requests: write
    steps:
      - uses: actions/stale@v10
        with:
          days-before-stale: 60
          days-before-close: 10
          exempt-draft-pr: true


  workflows:
    runs-on: ubuntu-latest
    name: 'Cleanup old workflow runs'
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 45
          keep_minimum_runs: 1
