name: OWASP

env:
  MAVEN_OPTS: -Djava.awt.headless=true

on:
  pull_request:
  schedule:
    - cron: "17 23 * * 0"
  workflow_dispatch:

jobs:
  build:
    name: Dependency Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'

      - name: OWASP Dependency Check
        continue-on-error: true
        run: mvn -U install -DnvdApiKey=${{ secrets.NVD_API_KEY }} -DskipTests -DskipITs -Dmaven.test.skip=true org.owasp:dependency-check-maven:check -fae -B -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -DfailBuildOnCVSS=5

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: target/dependency-check-report.sarif

      - name: Cleanup snapshots
        run: mvn clean build-helper:remove-project-artifact
