name: MSSQL Server Windows

on:
  pull_request:

jobs:
  build:
    name: MS SQL 2019 / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: 'windows-2019'
            tag: 'ltsc2019-sql2019'
          - os: 'windows-2022'
            tag: 'ltsc2022-sql2019'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - name: Set up JDK for build
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.b3p.nl -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Setup database engine for MS SQL
        run: .\.build\ci\mssql-start.ps1 -tag ${{ matrix.tag }}

      - name: Setup test environment for MS SQL
        run: .\.build\ci\mssql-setup.ps1

      - name: Priming build
        run: mvn --% install -Dmaven.test.skip=true --global-toolchains .github/windows-toolchains.xml -B -V -e -fae -q -Pmssql

      - name: Verify ${{ matrix.mssql }}
        run: mvn --% -e verify -B --global-toolchains .github/windows-toolchains.xml -Pmssql -T1 -Dtest.onlyITs=true

      - name: Clean artifacts from repository
        run: mvn --% clean build-helper:remove-project-artifact

      - name: Upload codecoverage
        uses: codecov/codecov-action@v2
