name: 'MS SQL Server Linux tests'

on:
  push:
    branches: [ master ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release' ) && format('ci-master-{0}', github.sha) || format('ci-master-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  build:
    name: "MS SQL ${{ matrix.mssql }} / Java ${{ matrix.java }}"
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        mssql: [ 2019-latest, 2022-latest ]
        java: [ 17 ]
        java_dist: [ 'zulu' ]

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 5

      - name: 'Set up JDK'
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.java_dist }}
          cache: 'maven'

      - name: "Setup test environment for MS SQL ${{ matrix.mssql }}"
        run: |
          ./.build/ci/mssql-start.sh ${{ matrix.mssql }}
          ./.build/ci/mssql-setup.sh

      - name: 'Priming build'
        run: mvn install -Dmaven.test.skip=true -B -V -e -fae -q -Pmssql

      - name: "Test ${{ matrix.mssql }}"
        run: mvn -e test -B -Pmssql

      - name: "Verify ${{ matrix.mssql }}"
        run: mvn -e verify -B -Pmssql -T1 -Dtest.onlyITs=true

      - name: 'Clean artifacts from repository'
        run: mvn clean build-helper:remove-project-artifact

      - name: 'Upload codecoverage'
        uses: codecov/codecov-action@v5
