name: MS SQL Server Windows tests

on: [push]

jobs:
  build:
    name: MS SQL 2019 / Java ${{ matrix.java }}
    runs-on: windows-2019
    strategy:
      matrix:
        java: [8, 11]
        java_dist: [ 'zulu' ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 11 for toolchains
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: ${{ matrix.java_dist }}
      - name: Set up JDK 8 for toolchains
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: ${{ matrix.java_dist }}
      - name: Set up JDK for build
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.java_dist }}

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.b3p.nl -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Setup database engine for MS SQL
        run: .\.build\ci\mssql-start.ps1

      - name: Setup test environment for MS SQL
        run: .\.build\ci\mssql-setup.ps1

      - name: Priming build
        run: mvn --% install -Dmaven.test.skip=true --global-toolchains .github/windows-toolchains.xml -B -V -e -fae -q -Pmssql

      - name: Verify ${{ matrix.mssql }}
        run: mvn --% -e verify -B --global-toolchains .github/windows-toolchains.xml -Pmssql -T1 -Dtest.onlyITs=true

      - name: Clean artifacts from repository
        run: mvn --% clean build-helper:remove-project-artifact

      - name: Upload codecoverage
        uses: codecov/codecov-action@v1