name: MS SQL Server Linux tests

on:
  push:

jobs:
  build:
    name: MS SQL ${{ matrix.mssql }} / Java ${{ matrix.java }}
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        mssql: [2019-latest]
        java: [ 11 ]
        java_dist: [ 'zulu' ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - name: Set up JDK for build
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.java_dist }}

      - name: Setup test environment for MS SQL ${{ matrix.mssql }}
        run: |
          ./.build/ci/mssql-start.sh ${{ matrix.mssql }}
          ./.build/ci/mssql-setup.sh

      - name: Priming build
        run: mvn install -Dmaven.test.skip=true --global-toolchains .github/ubuntu-toolchains.xml -B -V -e -fae -q -Pmssql

      - name: Verify ${{ matrix.mssql }}
        run: mvn -e verify -B --global-toolchains .github/ubuntu-toolchains.xml -Pmssql -T1 -Dtest.onlyITs=true

      - name: Clean artifacts from repository
        run: mvn clean build-helper:remove-project-artifact

      - name: Upload codecoverage
        uses: codecov/codecov-action@v2
