name: MS SQL Server Linux tests

on:
  push:
    branches: [ master ]
  pull_request:

concurrency: # cancel on PR pushes
  # More info: https://stackoverflow.com/a/68422069/253468
  group: ${{ github.workflow }}-${{ ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release' ) && format('ci-master-{0}', github.sha) || format('ci-master-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  build:
    name: MS SQL ${{ matrix.mssql }} / Java ${{ matrix.java }}
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        mssql: [ 2019-latest, 2022-latest ]
        java: [ 11 ]
        java_dist: [ 'zulu' ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 5
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - name: Set up JDK for build
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.java_dist }}

      - name: Setup test environment for MS SQL ${{ matrix.mssql }}
        run: |
          ./.build/ci/mssql-start.sh ${{ matrix.mssql }}
          ./.build/ci/mssql-setup.sh

      - name: Priming build
        run: mvn install -Dmaven.test.skip=true -B -V -e -fae -q -Pmssql

      - name: Test ${{ matrix.mssql }}
        run: mvn -e test -B -Pmssql

      - name: Verify ${{ matrix.mssql }}
        run: mvn -e verify -B -Pmssql -T1 -Dtest.onlyITs=true

      - name: Clean artifacts from repository
        run: mvn clean build-helper:remove-project-artifact

      - name: Upload codecoverage
        uses: codecov/codecov-action@v3
