name: Oracle tests

on:
  push:

jobs:
  build:
    name: Oracle ${{ matrix.oracle }} / Java ${{ matrix.java }}
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        java: [ 11 ]
        java_dist: [ 'temurin' ]
        oracle: ['18.4.0-full', '21.3.0-full']

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
          
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
            
      - name: Set up JDK for build
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.java_dist }}

      - name: Free up diskspace
        run: |
          docker container prune --force
          docker image prune -a --force
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet 
          df -h

      - name: Setup test environment for Oracle
        run: |
          ./.build/ci/oracle-start.sh ${{ matrix.oracle }}
          ./.build/ci/oracle-setup.sh

      - name: Priming build
        run: mvn install -Dmaven.test.skip=true -B -V -e -fae -q -Poracle --global-toolchains .github/ubuntu-toolchains.xml

      - name: Verify
        run: mvn -e verify -B -Poracle -T1 -Dtest.onlyITs=true --global-toolchains .github/ubuntu-toolchains.xml

      - name: Clean artifacts from repository
        run: mvn clean build-helper:remove-project-artifact

      - name: Upload codecoverage
        uses: codecov/codecov-action@v2
