name: Oracle tests

on:
  push:

concurrency: # cancel on PR pushes
  # More info: https://stackoverflow.com/a/68422069/253468
  group: ${{ github.workflow }}-${{ ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release' ) && format('ci-master-{0}', github.sha) || format('ci-master-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  build:
    name: Oracle ${{ matrix.oracle }} / Java ${{ matrix.java }}
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        java: [ 11 ]
        java_dist: [ 'temurin' ]
        oracle: [ '21.3.0-full' ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5

      - name: 'Set up JDK'
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.java_dist }}
          cache: 'maven'

      - name: Free up diskspace
        run: |
          docker container prune --force
          docker image prune -a --force
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet 
          df -h

      - name: Setup test environment for Oracle
        run: |
          ./.build/ci/oracle-start.sh ${{ matrix.oracle }}
          ./.build/ci/oracle-setup.sh

      - name: Priming build
        run: mvn install -Dmaven.test.skip=true -B -V -e -fae -q -Poracle

      - name: Test
        run: mvn -e test -B -Poracle

      - name: Verify
        run: mvn -e verify -B -Poracle -T1 -Dtest.onlyITs=true

      - name: Clean artifacts from repository
        run: mvn clean build-helper:remove-project-artifact

      - name: Upload codecoverage
        uses: codecov/codecov-action@v3
