name: 'Oracle tests'

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release' ) && format('ci-master-{0}', github.sha) || format('ci-master-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  build:
    name: "Java ${{ matrix.java }} / Oracle ${{ matrix.oracle }}"
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        java: [ 17, 21 ]
        java_dist: [ 'temurin' ]
        oracle: [ 'oracle-xe:21.3.0-full', 'oracle-free:23.7-full' ]

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 5

      - name: 'Set up JDK'
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.java_dist }}
          cache: 'maven'

      - name: 'Free up diskspace'
        run: |
          docker container prune --force
          docker image prune -a --force
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet 
          df -h

      - name: 'Setup test environment for Oracle'
        run: |
          ./.build/ci/oracle-start.sh ${{ matrix.oracle }}
          ./.build/ci/oracle-setup.sh

      - name: 'Priming build'
        run: mvn install -Dmaven.test.skip=true -B -V -e -fae -q -Poracle

      - name: 'Test'
        run: mvn -e test -B -Poracle

      - name: 'Verify'
        run: mvn -e verify -B -Poracle -T1 -Dtest.onlyITs=true

      - name: 'Clean artifacts from repository'
        run: mvn clean build-helper:remove-project-artifact

      - name: 'Upload codecoverage'
        uses: codecov/codecov-action@v5
