name: 'MSSQL Server Windows'

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release' ) && format('ci-master-{0}', github.sha) || format('ci-master-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  build:
    name: "MS SQL 2019 / ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'windows-2022'
            tag: 'ltsc2022-sql2019'

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 5

      - name: 'Set up JDK for build'
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'maven'

      - name: 'Login to b3p.nl'
        uses: docker/login-action@v3
        with:
          registry: docker.b3p.nl
          username: ${{ secrets.DOCKER_B3P_PULL_ACTOR }}
          password: ${{ secrets.DOCKER_B3P_PULL_TOKEN }}

      - name: 'Setup database engine for MS SQL'
        run: .\.build\ci\mssql-start.ps1 -tag ${{ matrix.tag }}

      - name: 'Setup test environment for MS SQL'
        run: .\.build\ci\mssql-setup.ps1

      - name: 'Priming build'
        run: mvn --% install -Dmaven.test.skip=true -B -V -e -fae -q -Pmssql

      - name: "Verify ${{ matrix.mssql }}"
        run: mvn --% -e verify -B -Pmssql -T1 -Dtest.onlyITs=true

      - name: 'Clean artifacts from repository'
        run: mvn --% clean build-helper:remove-project-artifact

      - name: 'Upload codecoverage'
        uses: codecov/codecov-action@v5
